//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatosD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IngresoClientesEntities : DbContext
    {
        public IngresoClientesEntities()
            : base("name=IngresoClientesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
    
        public virtual ObjectResult<sp_Ingreso_Clientes_Result> sp_Ingreso_Clientes(string strCedula_Cliente, string strNombre_Cliente, string strApellido_Cliente, string strTelefono_Cliente, string strDireccion_Cliente, string strCorreo_Cliente)
        {
            var strCedula_ClienteParameter = strCedula_Cliente != null ?
                new ObjectParameter("strCedula_Cliente", strCedula_Cliente) :
                new ObjectParameter("strCedula_Cliente", typeof(string));
    
            var strNombre_ClienteParameter = strNombre_Cliente != null ?
                new ObjectParameter("strNombre_Cliente", strNombre_Cliente) :
                new ObjectParameter("strNombre_Cliente", typeof(string));
    
            var strApellido_ClienteParameter = strApellido_Cliente != null ?
                new ObjectParameter("strApellido_Cliente", strApellido_Cliente) :
                new ObjectParameter("strApellido_Cliente", typeof(string));
    
            var strTelefono_ClienteParameter = strTelefono_Cliente != null ?
                new ObjectParameter("strTelefono_Cliente", strTelefono_Cliente) :
                new ObjectParameter("strTelefono_Cliente", typeof(string));
    
            var strDireccion_ClienteParameter = strDireccion_Cliente != null ?
                new ObjectParameter("strDireccion_Cliente", strDireccion_Cliente) :
                new ObjectParameter("strDireccion_Cliente", typeof(string));
    
            var strCorreo_ClienteParameter = strCorreo_Cliente != null ?
                new ObjectParameter("strCorreo_Cliente", strCorreo_Cliente) :
                new ObjectParameter("strCorreo_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Ingreso_Clientes_Result>("sp_Ingreso_Clientes", strCedula_ClienteParameter, strNombre_ClienteParameter, strApellido_ClienteParameter, strTelefono_ClienteParameter, strDireccion_ClienteParameter, strCorreo_ClienteParameter);
        }
    
        public virtual ObjectResult<sp_listar_clientes_Result> sp_listar_clientes(string filtro)
        {
            var filtroParameter = filtro != null ?
                new ObjectParameter("Filtro", filtro) :
                new ObjectParameter("Filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_clientes_Result>("sp_listar_clientes", filtroParameter);
        }
    
        public virtual ObjectResult<sp_actualizar_cliente_Result> sp_actualizar_cliente(string strCedula, string strNombre, string strApellido, string strTelefono, string strDireccion, string strCorreo)
        {
            var strCedulaParameter = strCedula != null ?
                new ObjectParameter("strCedula", strCedula) :
                new ObjectParameter("strCedula", typeof(string));
    
            var strNombreParameter = strNombre != null ?
                new ObjectParameter("strNombre", strNombre) :
                new ObjectParameter("strNombre", typeof(string));
    
            var strApellidoParameter = strApellido != null ?
                new ObjectParameter("strApellido", strApellido) :
                new ObjectParameter("strApellido", typeof(string));
    
            var strTelefonoParameter = strTelefono != null ?
                new ObjectParameter("strTelefono", strTelefono) :
                new ObjectParameter("strTelefono", typeof(string));
    
            var strDireccionParameter = strDireccion != null ?
                new ObjectParameter("strDireccion", strDireccion) :
                new ObjectParameter("strDireccion", typeof(string));
    
            var strCorreoParameter = strCorreo != null ?
                new ObjectParameter("strCorreo", strCorreo) :
                new ObjectParameter("strCorreo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_actualizar_cliente_Result>("sp_actualizar_cliente", strCedulaParameter, strNombreParameter, strApellidoParameter, strTelefonoParameter, strDireccionParameter, strCorreoParameter);
        }
    }
}
